version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_DATABASE: springbootmusictgbotbd
      MYSQL_ROOT_PASSWORD: 1212
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: java_app_container
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_DATABASE: springbootmusictgbotbd
      MYSQL_USER: root
      MYSQL_PASSWORD: 1212

volumes:
  db_data:
